### ISSUE TITLE
How to obtain the motif coordinates across the genome? 

### ISSUE THREAD

**Issue by Jyyin333** [zeitlingerlab/Shao_NG_2017#1]
Hi, shao:
   Very amazing job.
   And I have a question, In the figure 3a says "the top 200 motifs with the highest ChIP-nexus read counts were selected ", I wonder how you got the original motif coordinates file?
    Thanks.

**Comment by wanqingshao** [comment]
Hi,

Thanks for the question! I think you are referring to the figure 3a in the original ChIP-nexus paper He at. al 2015 Nature Biotechnology. I'm not an author on that paper and would encourage you to contact Julia (the corresponding author) for a precise answer.  

But for your reference, here's one way to obtain the coordinates of a motif in R. You can use BSgenome.Dmelanogaster.UCSC.dm3 and the vmatchPattern function from Biostrings, and do something like this: vmatchPattern(Motif_Pattern_like_CANNTG, Dmelanogaster, max.mismatch=0, min.mismatch=0, fixed = F). 

Wanqing

**Comment by Jyyin333** [comment]
> Hi,
> 
> Thanks for the question! I think you are referring to the figure 3a in the original ChIP-nexus paper He at. al 2015 Nature Biotechnology. I'm not an author on that paper and would encourage you to contact Julia (the corresponding author) for a precise answer.
> 
> But for your reference, here's one way to obtain the coordinates of a motif in R. You can use BSgenome.Dmelanogaster.UCSC.dm3 and the vmatchPattern function from Biostrings, and do something like this: vmatchPattern(Motif_Pattern_like_CANNTG, Dmelanogaster, max.mismatch=0, min.mismatch=0, fixed = F).
> 
> Wanqing

Thanks for your advice.
